[profile.default]
src="contracts"
bytecode_hash = "none"
optimizer_runs = 1000000
no_match_test = "FFI"

[profile.intense]
fuzz_runs = 10000
no_match_test = "FFI"

[profile.ffi]
ffi = true
match_test = "FFI"
no_match_test = "a^"
fuzz_runs = 1000

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"
op = "${RPC_URL_OPTIMISM}"
base = "${RPC_URL_BASE}"
base-goerli = "${RPC_URL_BASE_GOERLI}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}
op = {key = "${ETHERSCAN_API_KEY}"}
base = {key = "${ETHERSCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api"}
base-goerli = {key = "", chain = 84531, url = "https://api-goerli.basescan.org/api"}